#pragma once

#include <emscripten/bind.h>
#include <emscripten/val.h>

struct Domain {
    double start;
    double end;
};

EMSCRIPTEN_DECLARE_VAL_TYPE(Int8Array)
EMSCRIPTEN_DECLARE_VAL_TYPE(Int16Array)
EMSCRIPTEN_DECLARE_VAL_TYPE(Int32Array)
EMSCRIPTEN_DECLARE_VAL_TYPE(Uint8Array)
EMSCRIPTEN_DECLARE_VAL_TYPE(Uint16Array)
EMSCRIPTEN_DECLARE_VAL_TYPE(Uint32Array)
EMSCRIPTEN_DECLARE_VAL_TYPE(Float32Array)
EMSCRIPTEN_DECLARE_VAL_TYPE(Float64Array)
EMSCRIPTEN_DECLARE_VAL_TYPE(BigInt64Array)
EMSCRIPTEN_DECLARE_VAL_TYPE(BigUint64Array)

EMSCRIPTEN_DECLARE_VAL_TYPE(NumberArray)
EMSCRIPTEN_DECLARE_VAL_TYPE(EdgeArray)
EMSCRIPTEN_DECLARE_VAL_TYPE(WireArray)
EMSCRIPTEN_DECLARE_VAL_TYPE(FaceArray)
EMSCRIPTEN_DECLARE_VAL_TYPE(ShapeArray)
EMSCRIPTEN_DECLARE_VAL_TYPE(PntArray)
