// Copyright 2022-2023 the Chili authors. All rights reserved. MPL-2.0 license.

export type CommandKeys =
    | "doc.new"
    | "doc.save"
    | "doc.open"
    | "special.last"
    | "edit.undo"
    | "edit.redo"
    | "create.box"
    | "create.line"
    | "create.circle"
    | "create.rect"
    | "create.folder"
    | "create.group"
    | "create.polygon"
    | "convert.toPolygon"
    | "convert.prism"
    | "convert.revol"
    | "convert.fuse"
    | "modify.array"
    | "modify.move"
    | "modify.rotate"
    | "modify.mirror"
    | "modify.delete";
