// Part of the Chili3d Project, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

// AUTO-GENERATED by scripts/generate-shape-capabilities.mjs — do not edit by hand.
// Source of truth: packages/core/src/shape/{shapeFactory,shape,curve,surface}.ts.

export type ShapeParamKind =
    | "number"
    | "boolean"
    | "string"
    | "numberArray"
    | "xyz"
    | "xyzArray"
    | "plane"
    | "line"
    | "ref"
    | "refArray"
    | "curveRef"
    | "surfaceRef"
    | "refOrLine"
    | "refOrPlane"
    | "shapeType"
    | "enum";

export type ShapeReturnKind =
    | "solid"
    | "edge"
    | "wire"
    | "face"
    | "compound"
    | "shell"
    | "vertex"
    | "shape"
    | "shapeWithData";

export interface ShapeCapabilityParam {
    name: string;
    kind: ShapeParamKind;
    enum?: string[];
    required?: boolean;
}

export interface ShapeCapability {
    method: string;
    returnKind: ShapeReturnKind;
    params: ShapeCapabilityParam[];
}

export type QueryOwner =
    | "shape"
    | "vertex"
    | "edge"
    | "wire"
    | "face"
    | "solid"
    | "curve"
    | "line"
    | "conic"
    | "circle"
    | "ellipse"
    | "hyperbola"
    | "parabola"
    | "boundedCurve"
    | "bezierCurve"
    | "bsplineCurve"
    | "trimmedCurve"
    | "offsetCurve"
    | "complexCurve"
    | "surface"
    | "plateSurface"
    | "elementarySurface"
    | "offsetSurface"
    | "sweptSurface"
    | "rectangularTrimmedSurface"
    | "conicalSurface"
    | "cylindricalSurface"
    | "planeSurface"
    | "sphericalSurface"
    | "toroidalSurface"
    | "revolutionSurface";

export type QueryFamily = "shape" | "curve" | "surface";

export type QueryReturnKind = "data" | "curveRef" | "surfaceRef" | "shapeRef" | "refList" | "mutate";

export interface QueryCapability {
    method: string;
    name: string;
    owner: QueryOwner;
    family: QueryFamily;
    returnKind: QueryReturnKind;
    /** Concrete curve owners are validated at runtime against the target's curveType. */
    runtimeType?: string;
    params: ShapeCapabilityParam[];
}

export const shapeCapabilities: ShapeCapability[] = [
    { method: "edge", returnKind: "edge", params: [{ name: "curve", kind: "curveRef" }] },
    { method: "face", returnKind: "face", params: [{ name: "wire", kind: "refArray" }] },
    {
        method: "faceFromSurface",
        returnKind: "face",
        params: [
            { name: "wires", kind: "refArray" },
            { name: "sourceFace", kind: "ref" },
        ],
    },
    { method: "shell", returnKind: "shell", params: [{ name: "faces", kind: "refArray" }] },
    { method: "solid", returnKind: "solid", params: [{ name: "shells", kind: "refArray" }] },
    {
        method: "bezier",
        returnKind: "edge",
        params: [
            { name: "points", kind: "xyzArray" },
            { name: "weights", kind: "numberArray", required: false },
        ],
    },
    {
        method: "helix",
        returnKind: "wire",
        params: [
            { name: "origin", kind: "xyz" },
            { name: "normal", kind: "xyz" },
            { name: "xDir", kind: "xyz" },
            { name: "radius", kind: "number" },
            { name: "pitch", kind: "number" },
            { name: "angle", kind: "number" },
        ],
    },
    { method: "point", returnKind: "vertex", params: [{ name: "point", kind: "xyz" }] },
    {
        method: "line",
        returnKind: "edge",
        params: [
            { name: "start", kind: "xyz" },
            { name: "end", kind: "xyz" },
        ],
    },
    {
        method: "arc",
        returnKind: "edge",
        params: [
            { name: "normal", kind: "xyz" },
            { name: "center", kind: "xyz" },
            { name: "start", kind: "xyz" },
            { name: "angle", kind: "number" },
        ],
    },
    {
        method: "circle",
        returnKind: "edge",
        params: [
            { name: "normal", kind: "xyz" },
            { name: "center", kind: "xyz" },
            { name: "radius", kind: "number" },
        ],
    },
    {
        method: "rect",
        returnKind: "face",
        params: [
            { name: "plane", kind: "plane" },
            { name: "dx", kind: "number" },
            { name: "dy", kind: "number" },
        ],
    },
    { method: "polygon", returnKind: "wire", params: [{ name: "points", kind: "xyzArray" }] },
    {
        method: "box",
        returnKind: "solid",
        params: [
            { name: "plane", kind: "plane" },
            { name: "dx", kind: "number" },
            { name: "dy", kind: "number" },
            { name: "dz", kind: "number" },
        ],
    },
    {
        method: "ellipse",
        returnKind: "edge",
        params: [
            { name: "normal", kind: "xyz" },
            { name: "center", kind: "xyz" },
            { name: "xvec", kind: "xyz" },
            { name: "majorRadius", kind: "number" },
            { name: "minorRadius", kind: "number" },
        ],
    },
    {
        method: "cylinder",
        returnKind: "solid",
        params: [
            { name: "normal", kind: "xyz" },
            { name: "center", kind: "xyz" },
            { name: "radius", kind: "number" },
            { name: "dz", kind: "number" },
        ],
    },
    {
        method: "cone",
        returnKind: "solid",
        params: [
            { name: "normal", kind: "xyz" },
            { name: "center", kind: "xyz" },
            { name: "radius", kind: "number" },
            { name: "radiusUp", kind: "number" },
            { name: "dz", kind: "number" },
        ],
    },
    {
        method: "sphere",
        returnKind: "solid",
        params: [
            { name: "center", kind: "xyz" },
            { name: "radius", kind: "number" },
        ],
    },
    {
        method: "pyramid",
        returnKind: "solid",
        params: [
            { name: "plane", kind: "plane" },
            { name: "dx", kind: "number" },
            { name: "dy", kind: "number" },
            { name: "dz", kind: "number" },
        ],
    },
    { method: "wire", returnKind: "wire", params: [{ name: "edges", kind: "refArray" }] },
    {
        method: "prism",
        returnKind: "shape",
        params: [
            { name: "shape", kind: "ref" },
            { name: "vec", kind: "xyz" },
        ],
    },
    {
        method: "pushPull",
        returnKind: "shape",
        params: [
            { name: "shape", kind: "ref" },
            { name: "face", kind: "ref" },
            { name: "vec", kind: "xyz" },
        ],
    },
    {
        method: "sweep",
        returnKind: "shape",
        params: [
            { name: "profile", kind: "refArray" },
            { name: "path", kind: "ref" },
            { name: "isRoundCorner", kind: "boolean" },
        ],
    },
    {
        method: "revolve",
        returnKind: "shape",
        params: [
            { name: "profile", kind: "ref" },
            { name: "axis", kind: "line" },
            { name: "angle", kind: "number" },
        ],
    },
    {
        method: "booleanCommon",
        returnKind: "shape",
        params: [
            { name: "shape1", kind: "refArray" },
            { name: "shape2", kind: "refArray" },
        ],
    },
    {
        method: "booleanCut",
        returnKind: "shape",
        params: [
            { name: "shape1", kind: "refArray" },
            { name: "shape2", kind: "refArray" },
        ],
    },
    {
        method: "booleanFuse",
        returnKind: "shape",
        params: [
            { name: "shape1", kind: "refArray" },
            { name: "shape2", kind: "refArray" },
            { name: "simplifyShape", kind: "boolean" },
        ],
    },
    { method: "sewing", returnKind: "shape", params: [{ name: "shapes", kind: "refArray" }] },
    { method: "combine", returnKind: "compound", params: [{ name: "shapes", kind: "refArray" }] },
    {
        method: "makeThickSolidBySimple",
        returnKind: "shape",
        params: [
            { name: "shape", kind: "ref" },
            { name: "thickness", kind: "number" },
        ],
    },
    {
        method: "makeThickSolidByJoin",
        returnKind: "shape",
        params: [
            { name: "shape", kind: "ref" },
            { name: "openFaces", kind: "refArray" },
            { name: "thickness", kind: "number" },
            { name: "joinType", kind: "enum", enum: ["arc", "tangent", "intersection"] },
            { name: "mode", kind: "enum", enum: ["skin", "pipe", "rectoVerso"], required: false },
            { name: "intersection", kind: "boolean", required: false },
        ],
    },
    {
        method: "fillet",
        returnKind: "shape",
        params: [
            { name: "shape", kind: "ref" },
            { name: "edges", kind: "numberArray" },
            { name: "radius", kind: "number" },
        ],
    },
    {
        method: "chamfer",
        returnKind: "shape",
        params: [
            { name: "shape", kind: "ref" },
            { name: "edges", kind: "numberArray" },
            { name: "distance", kind: "number" },
        ],
    },
    {
        method: "fillet2d",
        returnKind: "face",
        params: [
            { name: "face", kind: "ref" },
            { name: "edge1", kind: "ref" },
            { name: "edge2", kind: "ref" },
            { name: "radius", kind: "number" },
        ],
    },
    {
        method: "chamfer2d",
        returnKind: "face",
        params: [
            { name: "face", kind: "ref" },
            { name: "edge1", kind: "ref" },
            { name: "edge2", kind: "ref" },
            { name: "distance", kind: "number" },
        ],
    },
    {
        method: "loft",
        returnKind: "shape",
        params: [
            { name: "sections", kind: "refArray" },
            { name: "isSolid", kind: "boolean" },
            { name: "isRuled", kind: "boolean" },
            { name: "continuity", kind: "enum", enum: ["c0", "g1", "c1", "g2", "c2", "c3", "cn"] },
        ],
    },
    {
        method: "removeFeature",
        returnKind: "shape",
        params: [
            { name: "shape", kind: "ref" },
            { name: "faces", kind: "refArray" },
        ],
    },
    {
        method: "removeFillet",
        returnKind: "shapeWithData",
        params: [
            { name: "shape", kind: "ref" },
            { name: "faces", kind: "refArray" },
        ],
    },
    {
        method: "removeSubShape",
        returnKind: "shape",
        params: [
            { name: "shape", kind: "ref" },
            { name: "subShapes", kind: "refArray" },
        ],
    },
    {
        method: "replaceSubShapes",
        returnKind: "shape",
        params: [
            { name: "shape", kind: "ref" },
            { name: "oldSubShapes", kind: "refArray" },
            { name: "newSubShapes", kind: "refArray" },
        ],
    },
    {
        method: "curveProjection",
        returnKind: "shape",
        params: [
            { name: "curve", kind: "ref" },
            { name: "targetFace", kind: "ref" },
            { name: "vec", kind: "xyz" },
        ],
    },
    {
        method: "simplifyShape",
        returnKind: "shape",
        params: [
            { name: "shape", kind: "ref" },
            { name: "removeEdges", kind: "boolean" },
            { name: "removeFaces", kind: "boolean" },
            { name: "keepShapes", kind: "refArray" },
            { name: "linearTolerance", kind: "number", required: false },
            { name: "angleTolerance", kind: "number", required: false },
        ],
    },
];

export const queryCapabilities: QueryCapability[] = [
    {
        method: "shape.shapeType",
        name: "shapeType",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    { method: "shape.id", name: "id", owner: "shape", family: "shape", returnKind: "data", params: [] },
    {
        method: "shape.matrix",
        name: "matrix",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    {
        method: "shape.isClosed",
        name: "isClosed",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    {
        method: "shape.isNull",
        name: "isNull",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    {
        method: "shape.isEqual",
        name: "isEqual",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [{ name: "other", kind: "ref" }],
    },
    {
        method: "shape.isSame",
        name: "isSame",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [{ name: "other", kind: "ref" }],
    },
    {
        method: "shape.isPartner",
        name: "isPartner",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [{ name: "other", kind: "ref" }],
    },
    {
        method: "shape.orientation",
        name: "orientation",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    {
        method: "shape.findAncestor",
        name: "findAncestor",
        owner: "shape",
        family: "shape",
        returnKind: "refList",
        params: [
            { name: "ancestorType", kind: "shapeType" },
            { name: "fromShape", kind: "ref" },
        ],
    },
    {
        method: "shape.findSubShapes",
        name: "findSubShapes",
        owner: "shape",
        family: "shape",
        returnKind: "refList",
        params: [{ name: "subshapeType", kind: "shapeType" }],
    },
    {
        method: "shape.directSubShapes",
        name: "directSubShapes",
        owner: "shape",
        family: "shape",
        returnKind: "refList",
        params: [],
    },
    {
        method: "shape.section",
        name: "section",
        owner: "shape",
        family: "shape",
        returnKind: "shapeRef",
        params: [{ name: "shape", kind: "refOrPlane" }],
    },
    {
        method: "shape.split",
        name: "split",
        owner: "shape",
        family: "shape",
        returnKind: "shapeRef",
        params: [
            { name: "shapes", kind: "refArray" },
            { name: "tolerance", kind: "number", required: false },
        ],
    },
    {
        method: "shape.reserve",
        name: "reserve",
        owner: "shape",
        family: "shape",
        returnKind: "mutate",
        params: [],
    },
    {
        method: "shape.clone",
        name: "clone",
        owner: "shape",
        family: "shape",
        returnKind: "shapeRef",
        params: [],
    },
    {
        method: "shape.hlr",
        name: "hlr",
        owner: "shape",
        family: "shape",
        returnKind: "shapeRef",
        params: [
            { name: "position", kind: "xyz" },
            { name: "direction", kind: "xyz" },
            { name: "xDir", kind: "xyz" },
        ],
    },
    {
        method: "shape.boundingBox",
        name: "boundingBox",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    {
        method: "shape.orientedBoundingBox",
        name: "orientedBoundingBox",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    {
        method: "shape.extremaDistance",
        name: "extremaDistance",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [{ name: "other", kind: "ref" }],
    },
    {
        method: "shape.checkShape",
        name: "checkShape",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    {
        method: "shape.checkFaces",
        name: "checkFaces",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    {
        method: "shape.fixShape",
        name: "fixShape",
        owner: "shape",
        family: "shape",
        returnKind: "shapeRef",
        params: [{ name: "tolerance", kind: "number" }],
    },
    {
        method: "shape.fixSmallFace",
        name: "fixSmallFace",
        owner: "shape",
        family: "shape",
        returnKind: "shapeRef",
        params: [{ name: "tolerance", kind: "number" }],
    },
    {
        method: "shape.fixSolid",
        name: "fixSolid",
        owner: "shape",
        family: "shape",
        returnKind: "shapeRef",
        params: [{ name: "tolerance", kind: "number" }],
    },
    {
        method: "shape.shellSewing",
        name: "shellSewing",
        owner: "shape",
        family: "shape",
        returnKind: "shapeRef",
        params: [{ name: "tolerance", kind: "number" }],
    },
    {
        method: "shape.setTolerance",
        name: "setTolerance",
        owner: "shape",
        family: "shape",
        returnKind: "mutate",
        params: [{ name: "tolerance", kind: "number" }],
    },
    {
        method: "shape.volume",
        name: "volume",
        owner: "shape",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    {
        method: "vertex.point",
        name: "point",
        owner: "vertex",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    {
        method: "edge.update",
        name: "update",
        owner: "edge",
        family: "shape",
        returnKind: "mutate",
        params: [{ name: "curve", kind: "curveRef" }],
    },
    {
        method: "edge.intersect",
        name: "intersect",
        owner: "edge",
        family: "shape",
        returnKind: "data",
        params: [{ name: "other", kind: "refOrLine" }],
    },
    { method: "edge.length", name: "length", owner: "edge", family: "shape", returnKind: "data", params: [] },
    {
        method: "edge.curve",
        name: "curve",
        owner: "edge",
        family: "shape",
        returnKind: "curveRef",
        params: [],
    },
    {
        method: "edge.firstParameter",
        name: "firstParameter",
        owner: "edge",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    {
        method: "edge.lastParameter",
        name: "lastParameter",
        owner: "edge",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    {
        method: "edge.pointAt",
        name: "pointAt",
        owner: "edge",
        family: "shape",
        returnKind: "data",
        params: [{ name: "parameter", kind: "number" }],
    },
    {
        method: "edge.startPoint",
        name: "startPoint",
        owner: "edge",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    {
        method: "edge.endPoint",
        name: "endPoint",
        owner: "edge",
        family: "shape",
        returnKind: "data",
        params: [],
    },
    { method: "edge.ends", name: "ends", owner: "edge", family: "shape", returnKind: "data", params: [] },
    {
        method: "edge.offset",
        name: "offset",
        owner: "edge",
        family: "shape",
        returnKind: "shapeRef",
        params: [
            { name: "distance", kind: "number" },
            { name: "dir", kind: "xyz" },
        ],
    },
    {
        method: "edge.trim",
        name: "trim",
        owner: "edge",
        family: "shape",
        returnKind: "shapeRef",
        params: [
            { name: "start", kind: "number" },
            { name: "end", kind: "number" },
        ],
    },
    {
        method: "edge.hasContinuity",
        name: "hasContinuity",
        owner: "edge",
        family: "shape",
        returnKind: "data",
        params: [
            { name: "face1", kind: "ref" },
            { name: "face2", kind: "ref" },
        ],
    },
    {
        method: "edge.continuity",
        name: "continuity",
        owner: "edge",
        family: "shape",
        returnKind: "data",
        params: [
            { name: "face1", kind: "ref" },
            { name: "face2", kind: "ref" },
        ],
    },
    {
        method: "wire.toFace",
        name: "toFace",
        owner: "wire",
        family: "shape",
        returnKind: "shapeRef",
        params: [],
    },
    {
        method: "wire.edgeLoop",
        name: "edgeLoop",
        owner: "wire",
        family: "shape",
        returnKind: "refList",
        params: [],
    },
    {
        method: "wire.offset",
        name: "offset",
        owner: "wire",
        family: "shape",
        returnKind: "shapeRef",
        params: [
            { name: "distance", kind: "number" },
            { name: "joinType", kind: "enum", enum: ["arc", "tangent", "intersection"] },
        ],
    },
    { method: "face.area", name: "area", owner: "face", family: "shape", returnKind: "data", params: [] },
    {
        method: "face.normal",
        name: "normal",
        owner: "face",
        family: "shape",
        returnKind: "data",
        params: [
            { name: "u", kind: "number" },
            { name: "v", kind: "number" },
        ],
    },
    {
        method: "face.outerWire",
        name: "outerWire",
        owner: "face",
        family: "shape",
        returnKind: "shapeRef",
        params: [],
    },
    {
        method: "face.surface",
        name: "surface",
        owner: "face",
        family: "shape",
        returnKind: "surfaceRef",
        params: [],
    },
    {
        method: "face.intersectLine",
        name: "intersectLine",
        owner: "face",
        family: "shape",
        returnKind: "data",
        params: [
            { name: "point", kind: "xyz" },
            { name: "direction", kind: "xyz" },
            { name: "tolerance", kind: "number", required: false },
        ],
    },
    {
        method: "face.segmentsOfEdgeOnFace",
        name: "segmentsOfEdgeOnFace",
        owner: "face",
        family: "shape",
        returnKind: "data",
        params: [{ name: "edge", kind: "ref" }],
    },
    {
        method: "face.containsPoint",
        name: "containsPoint",
        owner: "face",
        family: "shape",
        returnKind: "data",
        params: [
            { name: "point", kind: "xyz" },
            { name: "containsEdge", kind: "boolean" },
            { name: "tolerance", kind: "number" },
        ],
    },
    {
        method: "solid.containsPoint",
        name: "containsPoint",
        owner: "solid",
        family: "shape",
        returnKind: "data",
        params: [
            { name: "point", kind: "xyz" },
            { name: "containsSurface", kind: "boolean" },
            { name: "tolerance", kind: "number" },
        ],
    },
    {
        method: "curve.curveType",
        name: "curveType",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [],
    },
    {
        method: "curve.uniformAbscissaByLength",
        name: "uniformAbscissaByLength",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [{ name: "length", kind: "number" }],
    },
    {
        method: "curve.uniformAbscissaByCount",
        name: "uniformAbscissaByCount",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [{ name: "curveCount", kind: "number" }],
    },
    {
        method: "curve.length",
        name: "length",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [],
    },
    {
        method: "curve.parameter",
        name: "parameter",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [
            { name: "point", kind: "xyz" },
            { name: "tolerance", kind: "number" },
        ],
    },
    {
        method: "curve.firstParameter",
        name: "firstParameter",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [],
    },
    {
        method: "curve.lastParameter",
        name: "lastParameter",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [],
    },
    {
        method: "curve.project",
        name: "project",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [{ name: "point", kind: "xyz" }],
    },
    {
        method: "curve.value",
        name: "value",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [{ name: "parameter", kind: "number" }],
    },
    {
        method: "curve.isCN",
        name: "isCN",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [{ name: "n", kind: "number" }],
    },
    {
        method: "curve.trim",
        name: "trim",
        owner: "curve",
        family: "curve",
        returnKind: "curveRef",
        params: [
            { name: "u1", kind: "number" },
            { name: "u2", kind: "number" },
        ],
    },
    {
        method: "curve.d0",
        name: "d0",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [{ name: "u", kind: "number" }],
    },
    {
        method: "curve.d1",
        name: "d1",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [{ name: "u", kind: "number" }],
    },
    {
        method: "curve.d2",
        name: "d2",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [{ name: "u", kind: "number" }],
    },
    {
        method: "curve.d3",
        name: "d3",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [{ name: "u", kind: "number" }],
    },
    {
        method: "curve.dn",
        name: "dn",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [
            { name: "u", kind: "number" },
            { name: "n", kind: "number" },
        ],
    },
    {
        method: "curve.reverse",
        name: "reverse",
        owner: "curve",
        family: "curve",
        returnKind: "mutate",
        params: [],
    },
    {
        method: "curve.reversed",
        name: "reversed",
        owner: "curve",
        family: "curve",
        returnKind: "curveRef",
        params: [],
    },
    {
        method: "curve.nearestFromPoint",
        name: "nearestFromPoint",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [{ name: "point", kind: "xyz" }],
    },
    {
        method: "curve.nearestExtrema",
        name: "nearestExtrema",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [{ name: "curve", kind: "refOrLine" }],
    },
    {
        method: "curve.isClosed",
        name: "isClosed",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [],
    },
    {
        method: "curve.period",
        name: "period",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [],
    },
    {
        method: "curve.isPeriodic",
        name: "isPeriodic",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [],
    },
    {
        method: "curve.continuity",
        name: "continuity",
        owner: "curve",
        family: "curve",
        returnKind: "data",
        params: [],
    },
    {
        method: "line.direction",
        name: "direction",
        owner: "line",
        family: "curve",
        returnKind: "data",
        runtimeType: "line",
        params: [],
    },
    { method: "conic.axis", name: "axis", owner: "conic", family: "curve", returnKind: "data", params: [] },
    { method: "conic.xAxis", name: "xAxis", owner: "conic", family: "curve", returnKind: "data", params: [] },
    { method: "conic.yAxis", name: "yAxis", owner: "conic", family: "curve", returnKind: "data", params: [] },
    {
        method: "conic.eccentricity",
        name: "eccentricity",
        owner: "conic",
        family: "curve",
        returnKind: "data",
        params: [],
    },
    {
        method: "circle.center",
        name: "center",
        owner: "circle",
        family: "curve",
        returnKind: "data",
        runtimeType: "circle",
        params: [],
    },
    {
        method: "circle.radius",
        name: "radius",
        owner: "circle",
        family: "curve",
        returnKind: "data",
        runtimeType: "circle",
        params: [],
    },
    {
        method: "ellipse.center",
        name: "center",
        owner: "ellipse",
        family: "curve",
        returnKind: "data",
        runtimeType: "ellipse",
        params: [],
    },
    {
        method: "ellipse.focus1",
        name: "focus1",
        owner: "ellipse",
        family: "curve",
        returnKind: "data",
        runtimeType: "ellipse",
        params: [],
    },
    {
        method: "ellipse.focus2",
        name: "focus2",
        owner: "ellipse",
        family: "curve",
        returnKind: "data",
        runtimeType: "ellipse",
        params: [],
    },
    {
        method: "ellipse.majorRadius",
        name: "majorRadius",
        owner: "ellipse",
        family: "curve",
        returnKind: "data",
        runtimeType: "ellipse",
        params: [],
    },
    {
        method: "ellipse.minorRadius",
        name: "minorRadius",
        owner: "ellipse",
        family: "curve",
        returnKind: "data",
        runtimeType: "ellipse",
        params: [],
    },
    {
        method: "hyperbola.focal",
        name: "focal",
        owner: "hyperbola",
        family: "curve",
        returnKind: "data",
        runtimeType: "hyperbola",
        params: [],
    },
    {
        method: "hyperbola.location",
        name: "location",
        owner: "hyperbola",
        family: "curve",
        returnKind: "data",
        runtimeType: "hyperbola",
        params: [],
    },
    {
        method: "hyperbola.focus1",
        name: "focus1",
        owner: "hyperbola",
        family: "curve",
        returnKind: "data",
        runtimeType: "hyperbola",
        params: [],
    },
    {
        method: "hyperbola.focus2",
        name: "focus2",
        owner: "hyperbola",
        family: "curve",
        returnKind: "data",
        runtimeType: "hyperbola",
        params: [],
    },
    {
        method: "hyperbola.majorRadius",
        name: "majorRadius",
        owner: "hyperbola",
        family: "curve",
        returnKind: "data",
        runtimeType: "hyperbola",
        params: [],
    },
    {
        method: "hyperbola.minorRadius",
        name: "minorRadius",
        owner: "hyperbola",
        family: "curve",
        returnKind: "data",
        runtimeType: "hyperbola",
        params: [],
    },
    {
        method: "parabola.focal",
        name: "focal",
        owner: "parabola",
        family: "curve",
        returnKind: "data",
        runtimeType: "parabola",
        params: [],
    },
    {
        method: "parabola.focus",
        name: "focus",
        owner: "parabola",
        family: "curve",
        returnKind: "data",
        runtimeType: "parabola",
        params: [],
    },
    {
        method: "parabola.directrix",
        name: "directrix",
        owner: "parabola",
        family: "curve",
        returnKind: "data",
        runtimeType: "parabola",
        params: [],
    },
    {
        method: "boundedCurve.startPoint",
        name: "startPoint",
        owner: "boundedCurve",
        family: "curve",
        returnKind: "data",
        params: [],
    },
    {
        method: "boundedCurve.endPoint",
        name: "endPoint",
        owner: "boundedCurve",
        family: "curve",
        returnKind: "data",
        params: [],
    },
    {
        method: "bezierCurve.degree",
        name: "degree",
        owner: "bezierCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "bezierCurve",
        params: [],
    },
    {
        method: "bezierCurve.weight",
        name: "weight",
        owner: "bezierCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "bezierCurve",
        params: [{ name: "index", kind: "number" }],
    },
    {
        method: "bezierCurve.insertPoleAfter",
        name: "insertPoleAfter",
        owner: "bezierCurve",
        family: "curve",
        returnKind: "mutate",
        runtimeType: "bezierCurve",
        params: [
            { name: "index", kind: "number" },
            { name: "point", kind: "xyz" },
            { name: "weight", kind: "number", required: false },
        ],
    },
    {
        method: "bezierCurve.insertPoleBefore",
        name: "insertPoleBefore",
        owner: "bezierCurve",
        family: "curve",
        returnKind: "mutate",
        runtimeType: "bezierCurve",
        params: [
            { name: "index", kind: "number" },
            { name: "point", kind: "xyz" },
            { name: "weight", kind: "number", required: false },
        ],
    },
    {
        method: "bezierCurve.removePole",
        name: "removePole",
        owner: "bezierCurve",
        family: "curve",
        returnKind: "mutate",
        runtimeType: "bezierCurve",
        params: [{ name: "index", kind: "number" }],
    },
    {
        method: "bezierCurve.setPole",
        name: "setPole",
        owner: "bezierCurve",
        family: "curve",
        returnKind: "mutate",
        runtimeType: "bezierCurve",
        params: [
            { name: "index", kind: "number" },
            { name: "point", kind: "xyz" },
            { name: "weight", kind: "number", required: false },
        ],
    },
    {
        method: "bezierCurve.setWeight",
        name: "setWeight",
        owner: "bezierCurve",
        family: "curve",
        returnKind: "mutate",
        runtimeType: "bezierCurve",
        params: [
            { name: "index", kind: "number" },
            { name: "weight", kind: "number" },
        ],
    },
    {
        method: "bezierCurve.nbPoles",
        name: "nbPoles",
        owner: "bezierCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "bezierCurve",
        params: [],
    },
    {
        method: "bezierCurve.pole",
        name: "pole",
        owner: "bezierCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "bezierCurve",
        params: [{ name: "index", kind: "number" }],
    },
    {
        method: "bezierCurve.poles",
        name: "poles",
        owner: "bezierCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "bezierCurve",
        params: [],
    },
    {
        method: "bsplineCurve.degree",
        name: "degree",
        owner: "bsplineCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "bsplineCurve",
        params: [],
    },
    {
        method: "bsplineCurve.nbKnots",
        name: "nbKnots",
        owner: "bsplineCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "bsplineCurve",
        params: [],
    },
    {
        method: "bsplineCurve.knot",
        name: "knot",
        owner: "bsplineCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "bsplineCurve",
        params: [{ name: "index", kind: "number" }],
    },
    {
        method: "bsplineCurve.setKnot",
        name: "setKnot",
        owner: "bsplineCurve",
        family: "curve",
        returnKind: "mutate",
        runtimeType: "bsplineCurve",
        params: [
            { name: "index", kind: "number" },
            { name: "value", kind: "number" },
        ],
    },
    {
        method: "bsplineCurve.nbPoles",
        name: "nbPoles",
        owner: "bsplineCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "bsplineCurve",
        params: [],
    },
    {
        method: "bsplineCurve.pole",
        name: "pole",
        owner: "bsplineCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "bsplineCurve",
        params: [{ name: "index", kind: "number" }],
    },
    {
        method: "bsplineCurve.poles",
        name: "poles",
        owner: "bsplineCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "bsplineCurve",
        params: [],
    },
    {
        method: "bsplineCurve.weight",
        name: "weight",
        owner: "bsplineCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "bsplineCurve",
        params: [{ name: "index", kind: "number" }],
    },
    {
        method: "bsplineCurve.setWeight",
        name: "setWeight",
        owner: "bsplineCurve",
        family: "curve",
        returnKind: "mutate",
        runtimeType: "bsplineCurve",
        params: [
            { name: "index", kind: "number" },
            { name: "value", kind: "number" },
        ],
    },
    {
        method: "trimmedCurve.basisCurve",
        name: "basisCurve",
        owner: "trimmedCurve",
        family: "curve",
        returnKind: "curveRef",
        runtimeType: "trimmedCurve",
        params: [],
    },
    {
        method: "trimmedCurve.setTrim",
        name: "setTrim",
        owner: "trimmedCurve",
        family: "curve",
        returnKind: "mutate",
        runtimeType: "trimmedCurve",
        params: [
            { name: "u1", kind: "number" },
            { name: "u2", kind: "number" },
        ],
    },
    {
        method: "offsetCurve.basisCurve",
        name: "basisCurve",
        owner: "offsetCurve",
        family: "curve",
        returnKind: "curveRef",
        runtimeType: "offsetCurve",
        params: [],
    },
    {
        method: "offsetCurve.offset",
        name: "offset",
        owner: "offsetCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "offsetCurve",
        params: [],
    },
    {
        method: "offsetCurve.direction",
        name: "direction",
        owner: "offsetCurve",
        family: "curve",
        returnKind: "data",
        runtimeType: "offsetCurve",
        params: [],
    },
    {
        method: "complexCurve.nbCurves",
        name: "nbCurves",
        owner: "complexCurve",
        family: "curve",
        returnKind: "data",
        params: [],
    },
    {
        method: "complexCurve.curve",
        name: "curve",
        owner: "complexCurve",
        family: "curve",
        returnKind: "curveRef",
        params: [{ name: "index", kind: "number" }],
    },
    {
        method: "surface.nearestPoint",
        name: "nearestPoint",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [{ name: "point", kind: "xyz" }],
    },
    {
        method: "surface.project",
        name: "project",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [{ name: "point", kind: "xyz" }],
    },
    {
        method: "surface.projectCurve",
        name: "projectCurve",
        owner: "surface",
        family: "surface",
        returnKind: "curveRef",
        params: [{ name: "curve", kind: "curveRef" }],
    },
    {
        method: "surface.parameter",
        name: "parameter",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [
            { name: "point", kind: "xyz" },
            { name: "maxDistance", kind: "number" },
        ],
    },
    {
        method: "surface.continuity",
        name: "continuity",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "surface.uIso",
        name: "uIso",
        owner: "surface",
        family: "surface",
        returnKind: "curveRef",
        params: [{ name: "u", kind: "number" }],
    },
    {
        method: "surface.vIso",
        name: "vIso",
        owner: "surface",
        family: "surface",
        returnKind: "curveRef",
        params: [{ name: "v", kind: "number" }],
    },
    {
        method: "surface.isPlanar",
        name: "isPlanar",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "surface.isUClosed",
        name: "isUClosed",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "surface.isVClosed",
        name: "isVClosed",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "surface.isUPeriodic",
        name: "isUPeriodic",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "surface.isVPeriodic",
        name: "isVPeriodic",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "surface.vPeriod",
        name: "vPeriod",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "surface.uPeriod",
        name: "uPeriod",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "surface.bounds",
        name: "bounds",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "surface.isCNu",
        name: "isCNu",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [{ name: "n", kind: "number" }],
    },
    {
        method: "surface.isCNv",
        name: "isCNv",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [{ name: "n", kind: "number" }],
    },
    {
        method: "surface.d0",
        name: "d0",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [
            { name: "u", kind: "number" },
            { name: "v", kind: "number" },
        ],
    },
    {
        method: "surface.d1",
        name: "d1",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [
            { name: "u", kind: "number" },
            { name: "v", kind: "number" },
        ],
    },
    {
        method: "surface.d2",
        name: "d2",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [
            { name: "u", kind: "number" },
            { name: "v", kind: "number" },
        ],
    },
    {
        method: "surface.d3",
        name: "d3",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [
            { name: "u", kind: "number" },
            { name: "v", kind: "number" },
        ],
    },
    {
        method: "surface.dn",
        name: "dn",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [
            { name: "u", kind: "number" },
            { name: "v", kind: "number" },
            { name: "nu", kind: "number" },
            { name: "nv", kind: "number" },
        ],
    },
    {
        method: "surface.value",
        name: "value",
        owner: "surface",
        family: "surface",
        returnKind: "data",
        params: [
            { name: "u", kind: "number" },
            { name: "v", kind: "number" },
        ],
    },
    {
        method: "plateSurface.setBounds",
        name: "setBounds",
        owner: "plateSurface",
        family: "surface",
        returnKind: "mutate",
        params: [
            { name: "u1", kind: "number" },
            { name: "u2", kind: "number" },
            { name: "v1", kind: "number" },
            { name: "v2", kind: "number" },
        ],
    },
    {
        method: "elementarySurface.axis",
        name: "axis",
        owner: "elementarySurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "elementarySurface.coordinates",
        name: "coordinates",
        owner: "elementarySurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "elementarySurface.location",
        name: "location",
        owner: "elementarySurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "offsetSurface.offset",
        name: "offset",
        owner: "offsetSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "offsetSurface.basisSurface",
        name: "basisSurface",
        owner: "offsetSurface",
        family: "surface",
        returnKind: "surfaceRef",
        params: [],
    },
    {
        method: "sweptSurface.direction",
        name: "direction",
        owner: "sweptSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "sweptSurface.basisCurve",
        name: "basisCurve",
        owner: "sweptSurface",
        family: "surface",
        returnKind: "curveRef",
        params: [],
    },
    {
        method: "rectangularTrimmedSurface.basisSurface",
        name: "basisSurface",
        owner: "rectangularTrimmedSurface",
        family: "surface",
        returnKind: "surfaceRef",
        params: [],
    },
    {
        method: "rectangularTrimmedSurface.setUTrim",
        name: "setUTrim",
        owner: "rectangularTrimmedSurface",
        family: "surface",
        returnKind: "mutate",
        params: [
            { name: "u1", kind: "number" },
            { name: "u2", kind: "number" },
        ],
    },
    {
        method: "rectangularTrimmedSurface.setVTrim",
        name: "setVTrim",
        owner: "rectangularTrimmedSurface",
        family: "surface",
        returnKind: "mutate",
        params: [
            { name: "v1", kind: "number" },
            { name: "v2", kind: "number" },
        ],
    },
    {
        method: "rectangularTrimmedSurface.setTrim",
        name: "setTrim",
        owner: "rectangularTrimmedSurface",
        family: "surface",
        returnKind: "mutate",
        params: [
            { name: "u1", kind: "number" },
            { name: "u2", kind: "number" },
            { name: "v1", kind: "number" },
            { name: "v2", kind: "number" },
        ],
    },
    {
        method: "conicalSurface.semiAngle",
        name: "semiAngle",
        owner: "conicalSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "conicalSurface.setRadius",
        name: "setRadius",
        owner: "conicalSurface",
        family: "surface",
        returnKind: "mutate",
        params: [{ name: "value", kind: "number" }],
    },
    {
        method: "conicalSurface.apex",
        name: "apex",
        owner: "conicalSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "conicalSurface.refRadius",
        name: "refRadius",
        owner: "conicalSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "cylindricalSurface.radius",
        name: "radius",
        owner: "cylindricalSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "planeSurface.plane",
        name: "plane",
        owner: "planeSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "sphericalSurface.radius",
        name: "radius",
        owner: "sphericalSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "sphericalSurface.area",
        name: "area",
        owner: "sphericalSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "sphericalSurface.volume",
        name: "volume",
        owner: "sphericalSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "toroidalSurface.area",
        name: "area",
        owner: "toroidalSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "toroidalSurface.volume",
        name: "volume",
        owner: "toroidalSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "toroidalSurface.majorRadius",
        name: "majorRadius",
        owner: "toroidalSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "toroidalSurface.minorRadius",
        name: "minorRadius",
        owner: "toroidalSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "revolutionSurface.location",
        name: "location",
        owner: "revolutionSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
    {
        method: "revolutionSurface.referencePlane",
        name: "referencePlane",
        owner: "revolutionSurface",
        family: "surface",
        returnKind: "data",
        params: [],
    },
];

export const capabilitiesSource = `Available modeling capabilities (from IShapeFactory; units: mm, angles: degrees):
  edge(curve: curveRef) -> edge
  face(wire: refArray) -> face
  faceFromSurface(wires: refArray, sourceFace: ref) -> face
  shell(faces: refArray) -> shell
  solid(shells: refArray) -> solid
  bezier(points: xyzArray, weights: numberArray?) -> edge
  helix(origin: xyz, normal: xyz, xDir: xyz, radius: number, pitch: number, angle: number) -> wire
  point(point: xyz) -> vertex
  line(start: xyz, end: xyz) -> edge
  arc(normal: xyz, center: xyz, start: xyz, angle: number) -> edge
  circle(normal: xyz, center: xyz, radius: number) -> edge
  rect(plane: plane, dx: number, dy: number) -> face
  polygon(points: xyzArray) -> wire
  box(plane: plane, dx: number, dy: number, dz: number) -> solid
  ellipse(normal: xyz, center: xyz, xvec: xyz, majorRadius: number, minorRadius: number) -> edge
  cylinder(normal: xyz, center: xyz, radius: number, dz: number) -> solid
  cone(normal: xyz, center: xyz, radius: number, radiusUp: number, dz: number) -> solid
  sphere(center: xyz, radius: number) -> solid
  pyramid(plane: plane, dx: number, dy: number, dz: number) -> solid
  wire(edges: refArray) -> wire
  prism(shape: ref, vec: xyz) -> shape
  pushPull(shape: ref, face: ref, vec: xyz) -> shape
  sweep(profile: refArray, path: ref, isRoundCorner: boolean) -> shape
  revolve(profile: ref, axis: line, angle: number) -> shape
  booleanCommon(shape1: refArray, shape2: refArray) -> shape
  booleanCut(shape1: refArray, shape2: refArray) -> shape
  booleanFuse(shape1: refArray, shape2: refArray, simplifyShape: boolean) -> shape
  sewing(shapes: refArray) -> shape
  combine(shapes: refArray) -> compound
  makeThickSolidBySimple(shape: ref, thickness: number) -> shape
  makeThickSolidByJoin(shape: ref, openFaces: refArray, thickness: number, joinType: arc|tangent|intersection, mode: skin|pipe|rectoVerso?, intersection: boolean?) -> shape
  fillet(shape: ref, edges: numberArray, radius: number) -> shape
  chamfer(shape: ref, edges: numberArray, distance: number) -> shape
  fillet2d(face: ref, edge1: ref, edge2: ref, radius: number) -> face
  chamfer2d(face: ref, edge1: ref, edge2: ref, distance: number) -> face
  loft(sections: refArray, isSolid: boolean, isRuled: boolean, continuity: c0|g1|c1|g2|c2|c3|cn) -> shape
  removeFeature(shape: ref, faces: refArray) -> shape
  removeFillet(shape: ref, faces: refArray) -> shapeWithData
  removeSubShape(shape: ref, subShapes: refArray) -> shape
  replaceSubShapes(shape: ref, oldSubShapes: refArray, newSubShapes: refArray) -> shape
  curveProjection(curve: ref, targetFace: ref, vec: xyz) -> shape
  simplifyShape(shape: ref, removeEdges: boolean, removeFaces: boolean, keepShapes: refArray, linearTolerance: number?, angleTolerance: number?) -> shape
JSON encoding: XYZ={x,y,z}; Plane={origin:{x,y,z}, normal:{x,y,z}?, xvec:{x,y,z}?} — an XY-oriented plane through origin when normal is omitted; Line={point:{x,y,z},direction:{x,y,z}} — a point plus a direction, NOT {start,end} ("line(start,end)" above is a creation method that builds an edge; to revolve around an existing edge, query edge.ends and derive point/direction from them); a shape/ref parameter takes an op id from any run_program call on this document or an existing node id; number[] is a plain number array — for fillet/chamfer "edges" it takes edge indices in the order returned by shape.findSubShapes(target, edge), so run that query first and pick indices from the edges' geometry (e.g. via edge.ends); enum params list their allowed values inline (a|b|c). Geometric params (plane/center/normal) may be omitted and default to the origin/Z axis. Params marked with ? are optional and may be omitted; the factory default applies. A method returning "shapeWithData" (removeFillet) creates its node from the result's shape; array extras (newEdges) come back in "results" under "<opId>.<key>" as { count, refs, kind: "shape" } with refs named <opId>#<key>#0..n.
Placement: box/rect/pyramid — plane.origin is a CORNER, the shape extends +dx/+dy/+dz from it. cylinder/cone — center is the BASE-FACE center, the shape extends +dz along normal. sphere — center is the true center. To center a box at P use origin = P - (dx/2,dy/2,dz/2); to center a cylinder/cone at P use center = P - normal*(dz/2).
polygon: pass the corner points in PERIMETER ORDER, at least 3, ALL ON ONE PLANE, and REPEAT THE FIRST POINT as the last point to close the wire explicitly. An unclosed wire can still become a face, but prism/revolve on it sweeps an open SHELL instead of a solid — a silent wrong result that breaks downstream booleans and fillets. polygon returns a WIRE, not a face: chain wire.toFace for a face or feed the closed wire to prism/revolve. A self-crossing point order (bowtie) yields a degenerate near-zero-area face, not an error — order points around the perimeter.`;

export const queryApiDoc = `Shape query API (units: mm, angles: degrees). Run via run_program query ops:
{ "method": "<owner>.<name>", "target": "<ref>", "id": "q1", "args": { ... } }
- target: an op id, an existing node id, a sub-shape ref (q1#2), or a curve/surface ref.
- Refs persist across run_program calls on the same document and re-resolve against the live shape; a ref whose source node was deleted fails with a clear error — re-run the query that produced it.
- Every query op needs an "id"; its return value comes back in the response "results" under that id. Result encodings: data queries return the plain value; curve/surface-producing queries (edge.curve, face.surface, trimmedCurve.basisCurve, ...) return { ref, kind } where kind is "curve" or "surface" — pass ref as the target of follow-up queries, and only to members matching its kind; single-shape queries (wire.toFace, wire.offset, face.outerWire, edge.trim, ...) return { ref, kind: "shape" } — the ref works both as a query target and as a shape argument in creation ops; list queries (shape.findSubShapes, wire.edgeLoop) return { count, refs, kind: "shape" }; mutation queries (curve.reverse, trimmedCurve.setTrim, ...) return null and modify the target ref's geometry in place — the mutation is remembered and re-applied whenever the ref is re-resolved.
- Query ops never consume or delete the referenced node, and never create scene nodes.
- kind encodings: xyz={x,y,z}; plane/refOrPlane={origin:{x,y,z}, normal:{x,y,z}?, xvec:{x,y,z}?} (XY-oriented through origin when normal is omitted) or, for refOrPlane, a shape ref string; line/refOrLine={point:{x,y,z},direction:{x,y,z}} or a ref string; matrix={array:[16 numbers, column-major]}; shapeType one of solid|shell|face|wire|edge|vertex|compound|compoundSolid; ref/curveRef/surfaceRef take a ref string.
- Type hierarchy: circle/ellipse/hyperbola/parabola are conic; conic/line/bezierCurve/bsplineCurve/trimmedCurve/offsetCurve are curve — curve.* and conic.* members apply to those targets too. Surfaces likewise: cylindricalSurface/planeSurface/sphericalSurface/... are elementarySurface, and every *Surface is a surface. Use curve.curveType to check what a curve ref actually is.
- edge.curve ALWAYS yields a trimmedCurve (it carries the edge's parameter range), even for a straight or circular edge.
- Auto-derivation: curve-family queries accept an edge shape ref directly (edge.curve is applied for you), and surface-family queries accept a face shape ref (face.surface). Type-specific curve members (circle.radius, line.direction, ...) additionally unwrap a trimmedCurve to its basisCurve, so circle.radius works straight on an edge ref. curve.curveType is the exception — it reports the target's own type, so on an edge or trimmedCurve it says "trimmedCurve"; chain trimmedCurve.basisCurve (callable on an edge ref too) to classify the underlying curve. Mutation queries (curve.reverse, trimmedCurve.setTrim) are strict: they need an explicit curve ref from edge.curve.
- curve/surface refs come from edge.curve and face.surface; sub-shape refs from shape.findSubShapes / wire.edgeLoop. A face's SURFACE (face.surface → plane/cylinder/...) is NOT its boundary curve: to inspect the edges bounding a face (e.g. the circular rim of a cylinder's top face), run shape.findSubShapes with subshapeType=edge on the face or solid, then edge.curve on the edge refs.

shape.* (target must be a shape):
  shape.shapeType(target) -> "shape" | "compound" | "compoundSolid" | "solid" | "shell" | "face" | "wire" | "edge" | "vertex"
  shape.id(target) -> string
  shape.matrix(target) -> Matrix4
  shape.isClosed(target) -> boolean
  shape.isNull(target) -> boolean
  shape.isEqual(target, other: ref) -> boolean
  shape.isSame(target, other: ref) -> boolean
  shape.isPartner(target, other: ref) -> boolean
  shape.orientation(target) -> "forward" | "reversed" | "internal" | "external"
  shape.findAncestor(target, ancestorType: shapeType, fromShape: ref) -> { count, refs } — also registers sub-shape refs <id>#0..n
  shape.findSubShapes(target, subshapeType: shapeType) -> { count, refs } — also registers sub-shape refs <id>#0..n
  shape.directSubShapes(target) -> { count, refs } — also registers sub-shape refs <id>#0..n
  shape.section(target, shape: refOrPlane) -> shape ref (registered under the op id)
  shape.split(target, shapes: refArray, tolerance: number?) -> shape ref (registered under the op id)
  shape.reserve(target) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)
  shape.clone(target) -> shape ref (registered under the op id)
  shape.hlr(target, position: xyz, direction: xyz, xDir: xyz) -> shape ref (registered under the op id)
  shape.boundingBox(target) -> BoundingBox
  shape.orientedBoundingBox(target) -> OrientedBoundingBox
  shape.extremaDistance(target, other: ref) -> number
  shape.checkShape(target) -> boolean
  shape.checkFaces(target) -> { index: number; isValid: boolean; status: string[]; }[]
  shape.fixShape(target, tolerance: number) -> shape ref (registered under the op id)
  shape.fixSmallFace(target, tolerance: number) -> shape ref (registered under the op id)
  shape.fixSolid(target, tolerance: number) -> shape ref (registered under the op id)
  shape.shellSewing(target, tolerance: number) -> shape ref (registered under the op id)
  shape.setTolerance(target, tolerance: number) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)
  shape.volume(target) -> number

vertex.* (target must be a vertex):
  vertex.point(target) -> XYZ

edge.* (target must be an edge):
  edge.update(target, curve: curveRef) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)
  edge.intersect(target, other: refOrLine) -> { parameter: number; point: XYZ; }[]
  edge.length(target) -> number
  edge.curve(target) -> curve ref (registered under the op id)
  edge.firstParameter(target) -> number
  edge.lastParameter(target) -> number
  edge.pointAt(target, parameter: number) -> XYZ
  edge.startPoint(target) -> XYZ
  edge.endPoint(target) -> XYZ
  edge.ends(target) -> [start: XYZ, end: XYZ]
  edge.offset(target, distance: number, dir: xyz) -> shape ref (registered under the op id)
  edge.trim(target, start: number, end: number) -> shape ref (registered under the op id)
  edge.hasContinuity(target, face1: ref, face2: ref) -> boolean
  edge.continuity(target, face1: ref, face2: ref) -> "c0" | "g1" | "c1" | "g2" | "c2" | "c3" | "cn"

wire.* (target must be a wire):
  wire.toFace(target) -> shape ref (registered under the op id)
  wire.edgeLoop(target) -> { count, refs } — also registers sub-shape refs <id>#0..n
  wire.offset(target, distance: number, joinType: arc|tangent|intersection) -> shape ref (registered under the op id)

face.* (target must be a face):
  face.area(target) -> number
  face.normal(target, u: number, v: number) -> [point: XYZ, normal: XYZ]
  face.outerWire(target) -> shape ref (registered under the op id)
  face.surface(target) -> surface ref (registered under the op id)
  face.intersectLine(target, point: xyz, direction: xyz, tolerance: number?) -> XYZ | undefined
  face.segmentsOfEdgeOnFace(target, edge: ref) -> { start: number; end: number; } | undefined
  face.containsPoint(target, point: xyz, containsEdge: boolean, tolerance: number) -> boolean

solid.* (target must be a solid):
  solid.containsPoint(target, point: xyz, containsSurface: boolean, tolerance: number) -> boolean

curve.* (target must be a curve (or a subtype of it)):
  curve.curveType(target) -> "line" | "circle" | "ellipse" | "hyperbola" | "parabola" | "bezierCurve" | "bsplineCurve" | "offsetCurve" | "otherCurve" | "trimmedCurve"
  curve.uniformAbscissaByLength(target, length: number) -> XYZ[]
  curve.uniformAbscissaByCount(target, curveCount: number) -> XYZ[]
  curve.length(target) -> number
  curve.parameter(target, point: xyz, tolerance: number) -> number | undefined
  curve.firstParameter(target) -> number
  curve.lastParameter(target) -> number
  curve.project(target, point: xyz) -> XYZ[]
  curve.value(target, parameter: number) -> XYZ
  curve.isCN(target, n: number) -> boolean
  curve.trim(target, u1: number, u2: number) -> curve ref (registered under the op id)
  curve.d0(target, u: number) -> XYZ
  curve.d1(target, u: number) -> { point: XYZ; vec: XYZ; }
  curve.d2(target, u: number) -> { point: XYZ; vec1: XYZ; vec2: XYZ; }
  curve.d3(target, u: number) -> { point: XYZ; vec1: XYZ; vec2: XYZ; vec3: XYZ; }
  curve.dn(target, u: number, n: number) -> XYZ
  curve.reverse(target) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)
  curve.reversed(target) -> curve ref (registered under the op id)
  curve.nearestFromPoint(target, point: xyz) -> { point: XYZ; parameter: number; distance: number; }
  curve.nearestExtrema(target, curve: refOrLine) -> { isParallel: boolean; distance: number; p1: XYZ; p2: XYZ; u1: number; u2: number; } | undefined
  curve.isClosed(target) -> boolean
  curve.period(target) -> number
  curve.isPeriodic(target) -> boolean
  curve.continuity(target) -> "c0" | "g1" | "c1" | "g2" | "c2" | "c3" | "cn"

line.* (target must be a line (or a subtype of it)):
  line.direction(target) -> XYZ

conic.* (target must be a conic (or a subtype of it)):
  conic.axis(target) -> XYZ
  conic.xAxis(target) -> XYZ
  conic.yAxis(target) -> XYZ
  conic.eccentricity(target) -> number

circle.* (target must be a circle (or a subtype of it)):
  circle.center(target) -> XYZ
  circle.radius(target) -> number

ellipse.* (target must be an ellipse (or a subtype of it)):
  ellipse.center(target) -> XYZ
  ellipse.focus1(target) -> XYZ
  ellipse.focus2(target) -> XYZ
  ellipse.majorRadius(target) -> number
  ellipse.minorRadius(target) -> number

hyperbola.* (target must be a hyperbola (or a subtype of it)):
  hyperbola.focal(target) -> number
  hyperbola.location(target) -> XYZ
  hyperbola.focus1(target) -> XYZ
  hyperbola.focus2(target) -> XYZ
  hyperbola.majorRadius(target) -> number
  hyperbola.minorRadius(target) -> number

parabola.* (target must be a parabola (or a subtype of it)):
  parabola.focal(target) -> number
  parabola.focus(target) -> XYZ
  parabola.directrix(target) -> XYZ

boundedCurve.* (target must be a boundedCurve (or a subtype of it)):
  boundedCurve.startPoint(target) -> XYZ
  boundedCurve.endPoint(target) -> XYZ

bezierCurve.* (target must be a bezierCurve (or a subtype of it)):
  bezierCurve.degree(target) -> number
  bezierCurve.weight(target, index: number) -> number
  bezierCurve.insertPoleAfter(target, index: number, point: xyz, weight: number?) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)
  bezierCurve.insertPoleBefore(target, index: number, point: xyz, weight: number?) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)
  bezierCurve.removePole(target, index: number) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)
  bezierCurve.setPole(target, index: number, point: xyz, weight: number?) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)
  bezierCurve.setWeight(target, index: number, weight: number) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)
  bezierCurve.nbPoles(target) -> number
  bezierCurve.pole(target, index: number) -> XYZ
  bezierCurve.poles(target) -> XYZ[]

bsplineCurve.* (target must be a bsplineCurve (or a subtype of it)):
  bsplineCurve.degree(target) -> number
  bsplineCurve.nbKnots(target) -> number
  bsplineCurve.knot(target, index: number) -> number
  bsplineCurve.setKnot(target, index: number, value: number) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)
  bsplineCurve.nbPoles(target) -> number
  bsplineCurve.pole(target, index: number) -> XYZ
  bsplineCurve.poles(target) -> XYZ[]
  bsplineCurve.weight(target, index: number) -> number
  bsplineCurve.setWeight(target, index: number, value: number) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)

trimmedCurve.* (target must be a trimmedCurve (or a subtype of it)):
  trimmedCurve.basisCurve(target) -> curve ref (registered under the op id)
  trimmedCurve.setTrim(target, u1: number, u2: number) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)

offsetCurve.* (target must be an offsetCurve (or a subtype of it)):
  offsetCurve.basisCurve(target) -> curve ref (registered under the op id)
  offsetCurve.offset(target) -> number
  offsetCurve.direction(target) -> XYZ

complexCurve.* (target must be a complexCurve (or a subtype of it)):
  complexCurve.nbCurves(target) -> number
  complexCurve.curve(target, index: number) -> curve ref (registered under the op id)

surface.* (target must be a surface (or a subtype of it)):
  surface.nearestPoint(target, point: xyz) -> [XYZ, number] | undefined
  surface.project(target, point: xyz) -> XYZ[]
  surface.projectCurve(target, curve: curveRef) -> curve ref (registered under the op id)
  surface.parameter(target, point: xyz, maxDistance: number) -> { u: number; v: number; } | undefined
  surface.continuity(target) -> "c0" | "g1" | "c1" | "g2" | "c2" | "c3" | "cn"
  surface.uIso(target, u: number) -> curve ref (registered under the op id)
  surface.vIso(target, v: number) -> curve ref (registered under the op id)
  surface.isPlanar(target) -> boolean
  surface.isUClosed(target) -> boolean
  surface.isVClosed(target) -> boolean
  surface.isUPeriodic(target) -> boolean
  surface.isVPeriodic(target) -> boolean
  surface.vPeriod(target) -> number
  surface.uPeriod(target) -> number
  surface.bounds(target) -> { u1: number; u2: number; v1: number; v2: number; }
  surface.isCNu(target, n: number) -> boolean
  surface.isCNv(target, n: number) -> boolean
  surface.d0(target, u: number, v: number) -> XYZ
  surface.d1(target, u: number, v: number) -> { point: XYZ; d1u: XYZ; d1v: XYZ; }
  surface.d2(target, u: number, v: number) -> { point: XYZ; d1u: XYZ; d1v: XYZ; d2u: XYZ; d2v: XYZ; d2uv: XYZ; }
  surface.d3(target, u: number, v: number) -> { point: XYZ; d1u: XYZ; d1v: XYZ; d2u: XYZ; d2v: XYZ; d2uv: XYZ; d3u: XYZ; d3v: XYZ; d3uuv: XYZ; d3uvv: XYZ; }
  surface.dn(target, u: number, v: number, nu: number, nv: number) -> XYZ
  surface.value(target, u: number, v: number) -> XYZ

plateSurface.* (target must be a plateSurface (or a subtype of it)):
  plateSurface.setBounds(target, u1: number, u2: number, v1: number, v2: number) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)

elementarySurface.* (target must be an elementarySurface (or a subtype of it)):
  elementarySurface.axis(target) -> XYZ
  elementarySurface.coordinates(target) -> Plane
  elementarySurface.location(target) -> XYZ

offsetSurface.* (target must be an offsetSurface (or a subtype of it)):
  offsetSurface.offset(target) -> number
  offsetSurface.basisSurface(target) -> surface ref (registered under the op id)

sweptSurface.* (target must be a sweptSurface (or a subtype of it)):
  sweptSurface.direction(target) -> XYZ
  sweptSurface.basisCurve(target) -> curve ref (registered under the op id)

rectangularTrimmedSurface.* (target must be a rectangularTrimmedSurface (or a subtype of it)):
  rectangularTrimmedSurface.basisSurface(target) -> surface ref (registered under the op id)
  rectangularTrimmedSurface.setUTrim(target, u1: number, u2: number) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)
  rectangularTrimmedSurface.setVTrim(target, v1: number, v2: number) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)
  rectangularTrimmedSurface.setTrim(target, u1: number, u2: number, v1: number, v2: number) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)

conicalSurface.* (target must be a conicalSurface (or a subtype of it)):
  conicalSurface.semiAngle(target) -> number
  conicalSurface.setRadius(target, value: number) -> null — mutates the target ref's geometry in place (re-applied on ref refresh)
  conicalSurface.apex(target) -> XYZ
  conicalSurface.refRadius(target) -> number

cylindricalSurface.* (target must be a cylindricalSurface (or a subtype of it)):
  cylindricalSurface.radius(target) -> number

planeSurface.* (target must be a planeSurface (or a subtype of it)):
  planeSurface.plane(target) -> Plane

sphericalSurface.* (target must be a sphericalSurface (or a subtype of it)):
  sphericalSurface.radius(target) -> number
  sphericalSurface.area(target) -> number
  sphericalSurface.volume(target) -> number

toroidalSurface.* (target must be a toroidalSurface (or a subtype of it)):
  toroidalSurface.area(target) -> number
  toroidalSurface.volume(target) -> number
  toroidalSurface.majorRadius(target) -> number
  toroidalSurface.minorRadius(target) -> number

revolutionSurface.* (target must be a revolutionSurface (or a subtype of it)):
  revolutionSurface.location(target) -> XYZ
  revolutionSurface.referencePlane(target) -> Plane

Examples:
- Measure a solid: { "method": "shape.volume", "target": "<nodeId>", "id": "v" } -> results.v = 12000
- Face area of a box face: { "method": "shape.findSubShapes", "target": "b", "id": "f", "args": { "subshapeType": "face" } } then { "method": "face.area", "target": "f#0", "id": "a" }
- Face from a wire loop: { "method": "wire.toFace", "target": "<wireRef>", "id": "f" } -> results.f = { ref: "f", kind: "shape" }, then e.g. { "method": "face.area", "target": "f", "id": "a" }
- Classify a solid's edge: { "method": "shape.findSubShapes", "target": "<solidId>", "id": "e", "args": { "subshapeType": "edge" } }, then { "method": "trimmedCurve.basisCurve", "target": "e#0", "id": "c" }, then { "method": "curve.curveType", "target": "c", "id": "t" } — and when t is "circle", { "method": "circle.radius", "target": "e#0", "id": "r" } works directly on the edge ref.
- Surface bounds: { "method": "face.surface", "target": "f#0", "id": "s" } then { "method": "surface.bounds", "target": "s", "id": "uv" }`;
