// Part of the Chili3d Project, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

import type { IShape, StlExportOptions } from "@chili3d/core";

/**
 * Minimal triangle-soup input for the STL writer: a flat `position` buffer
 * (x,y,z per vertex) and a triangle `index` buffer. This is exactly the shape of
 * an OCCT `FaceMeshData`, but kept structural so it is trivially unit-testable
 * with plain arrays and decoupled from the geometry kernel.
 */
export interface StlMesh {
    position: ArrayLike<number>;
    index: ArrayLike<number>;
}

const HEADER_SIZE = 80;
const COUNT_SIZE = 4;
const TRIANGLE_SIZE = 50; // 12 floats (normal + 3 verts) * 4 bytes + 2-byte attribute

function vertex(position: ArrayLike<number>, i: number): [number, number, number] {
    const o = i * 3;
    return [position[o], position[o + 1], position[o + 2]];
}

/** Geometric (winding-consistent) unit normal of a triangle; (0,0,0) if degenerate. */
function triangleNormal(
    a: readonly [number, number, number],
    b: readonly [number, number, number],
    c: readonly [number, number, number],
): [number, number, number] {
    const ux = b[0] - a[0];
    const uy = b[1] - a[1];
    const uz = b[2] - a[2];
    const vx = c[0] - a[0];
    const vy = c[1] - a[1];
    const vz = c[2] - a[2];
    let nx = uy * vz - uz * vy;
    let ny = uz * vx - ux * vz;
    let nz = ux * vy - uy * vx;
    const len = Math.hypot(nx, ny, nz);
    if (len > 0) {
        nx /= len;
        ny /= len;
        nz /= len;
    }
    return [nx, ny, nz];
}

function triangleCount(meshes: StlMesh[]): number {
    let total = 0;
    for (const mesh of meshes) {
        total += Math.floor(mesh.index.length / 3);
    }
    return total;
}

function writeBinary(meshes: StlMesh[], triangles: number): Uint8Array {
    const buffer = new ArrayBuffer(HEADER_SIZE + COUNT_SIZE + triangles * TRIANGLE_SIZE);
    const view = new DataView(buffer);
    // 80-byte header. Must NOT start with "solid" (that marks an ASCII file).
    const header = "Binary STL generated by Chili3D";
    for (let i = 0; i < header.length && i < HEADER_SIZE; i++) {
        view.setUint8(i, header.charCodeAt(i));
    }
    view.setUint32(HEADER_SIZE, triangles, true);

    let offset = HEADER_SIZE + COUNT_SIZE;
    const writeVec = (v: readonly [number, number, number]) => {
        view.setFloat32(offset, v[0], true);
        view.setFloat32(offset + 4, v[1], true);
        view.setFloat32(offset + 8, v[2], true);
        offset += 12;
    };

    for (const mesh of meshes) {
        const { position, index } = mesh;
        const tris = Math.floor(index.length / 3);
        for (let t = 0; t < tris; t++) {
            const a = vertex(position, index[t * 3]);
            const b = vertex(position, index[t * 3 + 1]);
            const c = vertex(position, index[t * 3 + 2]);
            writeVec(triangleNormal(a, b, c));
            writeVec(a);
            writeVec(b);
            writeVec(c);
            view.setUint16(offset, 0, true); // attribute byte count
            offset += 2;
        }
    }

    return new Uint8Array(buffer);
}

function fmt(n: number): string {
    return Object.is(n, -0) ? "0" : String(n);
}

function writeAscii(meshes: StlMesh[], name: string): Uint8Array {
    const lines: string[] = [`solid ${name}`];
    for (const mesh of meshes) {
        const { position, index } = mesh;
        const tris = Math.floor(index.length / 3);
        for (let t = 0; t < tris; t++) {
            const a = vertex(position, index[t * 3]);
            const b = vertex(position, index[t * 3 + 1]);
            const c = vertex(position, index[t * 3 + 2]);
            const n = triangleNormal(a, b, c);
            lines.push(`  facet normal ${fmt(n[0])} ${fmt(n[1])} ${fmt(n[2])}`);
            lines.push("    outer loop");
            lines.push(`      vertex ${fmt(a[0])} ${fmt(a[1])} ${fmt(a[2])}`);
            lines.push(`      vertex ${fmt(b[0])} ${fmt(b[1])} ${fmt(b[2])}`);
            lines.push(`      vertex ${fmt(c[0])} ${fmt(c[1])} ${fmt(c[2])}`);
            lines.push("    endloop");
            lines.push("  endfacet");
        }
    }
    lines.push(`endsolid ${name}`);
    return new TextEncoder().encode(`${lines.join("\n")}\n`);
}

/**
 * Serialize triangle meshes to STL bytes. Binary by default. Pure data → pure
 * bytes: no geometry kernel, no DOM, no Three.js, so it runs headless and is
 * directly unit-testable.
 */
export function meshesToStl(meshes: StlMesh[], options?: StlExportOptions): Uint8Array {
    const binary = options?.binary ?? true;
    if (binary) {
        return writeBinary(meshes, triangleCount(meshes));
    }
    return writeAscii(meshes, options?.name ?? "chili3d");
}

/**
 * Headless STL export for shapes. Reads each shape's lazily-tessellated OCCT face
 * mesh (`shape.mesh.faces`) — which needs no visual layer — and writes STL bytes.
 * This is the UI-independent core export used by both the browser app and the MCP
 * server.
 */
export function shapesToStl(shapes: IShape[], options?: StlExportOptions): Uint8Array {
    const meshes: StlMesh[] = [];
    for (const shape of shapes) {
        const faces = shape.mesh.faces;
        if (faces && faces.index.length > 0) {
            meshes.push({ position: faces.position, index: faces.index });
        }
    }
    return meshesToStl(meshes, options);
}
